services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-cinema-local
    restart: always
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: 1607
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis-cinema:
    image: redis:alpine
    container_name: redis-cinema-local
    restart: always
    ports:
      - "6379:6379"
  # zookeeper:
  #   image: wurstmeister/zookeeper:latest
  #   container_name: zookeeper-djnd-cinema
  #   ports:
  #     - "2181:2181"

  # kafka-broker:
  #   image: wurstmeister/kafka:latest
  #   container_name: kafka-broker-djnd-cinema
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: localhost
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper